table Territories
	lineageTag: 353b2fab-9798-4035-afca-a28f49c1412e

	column Region
		dataType: string
		lineageTag: 29b6b784-efd8-4941-ad88-46a0c98942f9
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Territory
		dataType: string
		lineageTag: d718bf26-fb5e-4e0a-bcdd-4b1089f7d40d
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Country
		dataType: string
		isHidden
		lineageTag: a77c71c4-e669-48bf-a735-0b48c22d54fa
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column TerritorySeq
		dataType: string
		isHidden
		lineageTag: a439a7cc-f999-4b79-bd89-0cbd189169f3
		summarizeBy: none
		sourceColumn: TerritorySeq

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'State Or Province'
		dataType: string
		lineageTag: e8b12240-4547-4110-a367-52a76c2d9e0e
		summarizeBy: none
		sourceColumn: State Or Province

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Territories-cce59963-af31-4ea3-b1a5-c2b42f20283f = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://microsoft-my.sharepoint.com/personal/misewell_microsoft_com/Documents/Documents/GitHub/ContosoBI/Contoso%20-%20Sales%20-%20Current%20Release/Contoso%20-%20Dynamics%20365%20Sales%20Source%20Data.xlsx"), null, true),
				    TerritoriesTbl_Table = Source{[Item="TerritoriesTbl",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(TerritoriesTbl_Table,{{"Country", type text}, {"State Or Province", type text}, {"Region", type text}, {"Territory", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Factor", "ParentTerritorySeq", "ParentTerritoryFactor", "Distribution%", "DistributionAccumulation"})
				in
				    #"Removed Columns"

	changedProperty = IsHidden

	annotation PBI_QueryRelationships = {"columnCount":4,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Territories/Changed Type.{Country,0}","Section1/Territories/Changed Type.{State Or Province Abbreviation,1}","Section1/Territories/Changed Type.{Region,2}","Section1/Territories/Changed Type.{Territory,3}"],"ColumnCount":4,"KeyColumnNames":[],"ColumnIdentities":["Section1/Territories/Changed Type.{Country,0}","Section1/Territories/Changed Type.{State Or Province Abbreviation,1}","Section1/Territories/Changed Type.{Region,2}","Section1/Territories/Changed Type.{Territory,3}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

